@HostAddress = http://localhost:5238/api

##

POST {{HostAddress}}/users/register
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "juan@gmail.com",
    "password": "123123",
    "passwordConfirmation": "123123"
}

###

POST {{HostAddress}}/users/login
Content-Type: application/json

{
    "email": "juan@gmail.com",
    "password": "123123",
    "rememberMe": false
}

###

POST {{HostAddress}}/users/logout

###

POST {{HostAddress}}/posts
Content-Type: application/json

{
    "title": "My First Post 2",
    "content": "This is the content of my first post.",
    "categoryId": 1,
    "tagNames": ["Nodejs", "Express", "MongoDB", "Backend"]
}

### Publicar un post
PATCH {{HostAddress}}/posts/5/publish

### 1. Prueba por defecto (Debería traer la Página 1 con 10 elementos)
GET {{HostAddress}}/posts
Accept: application/json

### 2. Prueba pidiendo la Página 2 explícitamente
GET {{HostAddress}}/posts?page=2
Accept: application/json

### 3. Prueba cambiando la cantidad de elementos (Página 1, pero solo 5 posts)
GET {{HostAddress}}/posts?page=1&pageSize=5
Accept: application/json

### 4. Prueba de seguridad (Enviando una página inválida como 0 o negativa)
# El backend debería corregirlo automáticamente y devolver la página 1
GET {{HostAddress}}/posts?page=0&pageSize=10
Accept: application/json

### 5. Prueba de seguridad de límites (Pidiendo demasiados elementos)
# El backend debería limitarlo a 50 (según la regla que pusimos)
GET {{HostAddress}}/posts?page=1&pageSize=1000
Accept: application/json

### GET POST BY ID
GET {{HostAddress}}/posts/5
Accept: application/json

### GET Profile
GET {{HostAddress}}/users/me
Accept: application/json

### Create Category
POST {{HostAddress}}/categories
Content-Type: application/json

{
    "name": "Technology"
}

### Get All Categories
GET {{HostAddress}}/categories
Accept: application/json

