@Api_HostAddress = http://localhost:5238/api

##

POST {{Api_HostAddress}}/users/register
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "juan@gmail.com",
    "password": "123123",
    "passwordConfirmation": "123123"
}

###

POST {{Api_HostAddress}}/users/login
Content-Type: application/json

{
    "email": "juan@gmail.com",
    "password": "123123",
    "rememberMe": false
}

###

POST {{Api_HostAddress}}/users/logout

